name = "Blab"
uuid = "5e69d6fc-a5d6-414b-94d7-87aeca1b086c"
version = "0.1.0"
authors = ["Barak Bercovitz <barakber@gmail.com>"]

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Indicators = "70c4c096-89a6-5ec6-8236-da8aa3bd86fd"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MLJXGBoostInterface = "54119dfa-1dab-4055-a167-80440f4f7a91"
PersistenceDiagrams = "90b4794c-894b-4756-a0f8-5efeb5ddf7ae"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Ripserer = "aa79e827-bd0b-42a8-9f10-2b302677a641"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
XGBoost = "009559a3-9522-5dbb-924b-0b6ed2b22bb9"

[compat]
Indicators = "0.8.2"
MLJ = "0.19.2"
MLJXGBoostInterface = "0.3.13"
PersistenceDiagrams = "0.9.10"
Ripserer = "0.16.16"
Tables = "1.12.1"
XGBoost = "2.5.2"
